### ISSUE TITLE
Hi, just small problem with extension Version

### ISSUE THREAD

**Issue by reset77** [sokolinthesky/JsonLibraryImportExport#1]
![Screenshot 2024-12-30 095219](https://github.com/user-attachments/assets/85542302-1f63-485c-ac7e-265147ce1f34)

The extension is really good but seems to have trouble to update, seems it installs V1.0, but the update is 1.0.0, but it doesn't update, restarting Playnite always prompt to update it again

Seems to be an issue with manifest and plugin versions. 1.0 and 1.0.0 - Playnite reports it as new/different version.

Thanks

**Comment by sokolinthesky** [comment]
Hi, thank you for the ticket. I fixed manifest, It should work now
